var V='home',cart=[],D={items:[],batches:[],sales:[]};
D.shop={};try{var sv=localStorage.getItem('medstore_v1');if(sv)D=JSON.parse(sv)}catch(e){}
function okS(){return D.sales.filter(function(s){return !s.ret})}
function pays(){D.pay=D.pay||[];return D.pay}
function gstRep(){var m=today().slice(0,7),t={};okS().filter(function(s){return s.date.slice(0,7)===m}).forEach(function(s){(s.lines||[]).forEach(function(l){var a=l.q*l.mrp*(1-s.disc/100),g=a-a/(1+l.gst/100),o=t[l.gst]||(t[l.gst]={tx:0,g:0});o.tx+=a-g;o.g+=g})});var k=Object.keys(t);return '<div class="sheet"><h2>GST this month (sales)</h2>'+(k.length?'<div class="rep"><table style="width:100%;font-size:14px"><tr><th align="left">GST</th><th align="right">Taxable</th><th align="right">GST</th></tr>'+k.map(function(r){return '<tr><td>'+r+'%</td><td align="right">'+rp(t[r].tx)+'</td><td align="right">'+rp(t[r].g)+'</td></tr>'}).join('')+'</table></div>':'<div class="empty">No sales this month.</div>')+'</div>'}
function waBill(n){var s=D.sales.find(function(x){return x.no===n}),h=D.shop||{},p=(s.ph||'').replace(/\D/g,'');if(p.length===10)p='91'+p;
  var t=(h.name||'Medical Store')+'\nBill #'+s.no+' · '+s.date+'\n'+(s.lines||[]).map(function(l){return l.name+' x'+l.q+' = '+rp(l.q*l.mrp)}).join('\n')+(s.disc?'\nDiscount '+s.disc+'%':'')+'\nTotal: '+rp(s.total)+'\nThank you. Get well soon.';
  window.open('https://wa.me/'+p+'?text='+encodeURIComponent(t))}
function waOrder(){var t='Order list:\n'+shortList().map(function(i){return '- '+i.name+' : '+Math.max(i.min*2-qty(i.id),1)}).join('\n');window.open('https://wa.me/?text='+encodeURIComponent(t))}
function retBill(n){var s=D.sales.find(function(x){return x.no===n});if(!s||s.ret)return;if(!confirm('Return all items of Bill #'+n+'? Stock will be added back.'))return;(s.lines||[]).forEach(function(l){var b=D.batches.find(function(x){return x.id===l.bid});if(b)b.qty+=l.q});s.ret=true;save();draw()}
function recvPay(c){var a=+prompt('Amount received from '+c+' (Rs)');if(!a||a<=0)return;pays().push({c:c,a:a,date:today()});save();draw()}
function bk(){if(!(D.sales.length||D.batches.length))return '';if(D.lastBackup&&dto(D.lastBackup)>-7)return '';return '<div class="warnbox" onclick="go(\'settings\')">⚠️ Backup not taken in the last 7 days. Tap here to download a backup.</div>'}
function save(){try{localStorage.setItem('medstore_v1',JSON.stringify(D))}catch(e){}}
function $(i){return document.getElementById(i)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function esc(t){return String(t).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function rs(n){return '₹'+Math.round(n).toLocaleString('en-IN')}
function today(){return new Date().toISOString().slice(0,10)}
function dto(d){return Math.round((new Date(d)-new Date(today()))/864e5)}
function item(id){return D.items.find(function(i){return i.id===id})}
function live(id){return D.batches.filter(function(b){return b.itemId===id&&b.qty>0&&dto(b.exp)>=0}).sort(function(a,b){return a.exp<b.exp?-1:1})}
function qty(id){return live(id).reduce(function(a,b){return a+b.qty},0)}
function shortList(){return D.items.filter(function(i){return qty(i.id)<=i.min})}
function expList(){return D.batches.filter(function(b){return b.qty>0&&dto(b.exp)<=90}).sort(function(a,b){return a.exp<b.exp?-1:1})}
var T={home:'',sale:'New Bill',purchase:'Add Stock',stock:'Stock',items:'Medicines',expiry:'Expiry',short:'Short Stock',report:'Sales Report',credit:'Udhaar',settings:'Settings',bill:'Bill'};var BILL=0;
function rp(n){return '₹'+n.toFixed(2)}
function subs(i){if(!i.salt)return[];return D.items.filter(function(x){return x.id!==i.id&&x.salt&&x.salt.toLowerCase()===i.salt.toLowerCase()&&qty(x.id)>0})}
var NAV=[['home','🏠','Home'],['sale','🧾','Bill'],['purchase','🛒','Add Stock',1],['stock','📦','Stock'],['items','💊','Medicines',1],['expiry','⏳','Expiry',1],['short','⚠️','Short Stock',1],['report','📊','Report'],['credit','💳','Udhaar',1],['settings','⚙️','Settings',1]];
var FIRST=null;
function go(v){V=v;window.scrollTo(0,0);draw()}
function draw(){
  $('nv').innerHTML='<div class="brand">💊 Medical Store</div>'+NAV.map(function(n){return '<button class="'+(V===n[0]?'on':'')+(n[3]?' d':'')+'" onclick="go(\''+n[0]+'\')"><span>'+n[1]+'</span>'+n[2]+'</button>'}).join('');
  var h=V==='home'?'':'<div class="top sm"><button onclick="go(\'home\')" aria-label="Back">←</button><h1>'+T[V]+'</h1></div>';
  $('app').innerHTML=h+VIEW[V]();if(V==='stock')fillStock('');if(V==='sale'){fillPick('');if(window.innerWidth>=900)$('pq').focus()}}
function tile(v,ic,t,b){return '<button class="tile" onclick="go(\''+v+'\')">'+(b?'<span class="badge">'+b+'</span>':'')+'<div class="ic">'+ic+'</div>'+t+'</button>'}
var VIEW={
home:function(){
  var t=okS().filter(function(s){return s.date===today()}),amt=t.reduce(function(a,s){return a+s.total},0),pf=t.reduce(function(a,s){return a+s.profit},0);
  return '<div class="top"><h1>'+esc((D.shop&&D.shop.name)||'My Medical Store')+'</h1></div><div class="sheet pull"><div class="hero"><small>Today\'s sale</small><b>'+rs(amt)+'</b><div class="row"><span>Profit <b>'+rs(pf)+'</b></span><span>Bills <b>'+t.length+'</b></span></div></div>'+
  bk()+'<div class="tiles">'+tile('sale','🧾','New Bill')+tile('purchase','🛒','Add Stock')+tile('stock','📦','Stock')+tile('items','💊','Medicines')+tile('expiry','⏳','Expiry',expList().length)+tile('short','⚠️','Short Stock',shortList().length)+tile('report','📊','Sales Report')+tile('credit','💳','Udhaar')+tile('settings','⚙️','Settings')+'</div></div>'},
stock:function(){return '<div class="sheet"><label>Search medicine</label><input id="q" placeholder="Type name..." oninput="fillStock(this.value)"><div id="lst"></div></div>'},
sale:function(){
  var tot=0;cart.forEach(function(c){tot+=c.q*c.mrp});
  return '<div class="sheet"><div class="cols"><div><label>Search medicine</label><input id="pq" placeholder="Type name, tap or press Enter to add" oninput="fillPick(this.value)" onkeydown="pk(event)"><div id="pick"></div></div><div>'+
  '<h2>Bill</h2>'+(cart.length?cart.map(function(c,x){return '<div class="li"><div class="m"><b>'+esc(c.name)+'</b><span>'+rs(c.mrp)+' each</span></div><div class="stp"><button onclick="chg('+x+',-1)">−</button><b>'+c.q+'</b><button onclick="chg('+x+',1)">+</button></div><div class="q" style="min-width:70px">'+rs(c.q*c.mrp)+'</div></div>'}).join('')+'<div class="total"><span>Total</span><b id="gt">'+rs(tot)+'</b></div><div class="two"><div><label>Customer name</label><input id="cn" placeholder="Walk-in"></div><div><label>Phone (for WhatsApp)</label><input id="cph" type="tel" inputmode="numeric"></div><div><label>Doctor name</label><input id="dr"></div><div><label>Payment</label><select id="pm2"><option>Cash</option><option>UPI</option><option>Card</option><option>Credit</option></select></div><div><label>Discount %</label><input id="ds" type="number" inputmode="decimal" value="0" oninput="upd()"></div></div><button class="btn" onclick="finish()">Save Bill</button>':'<div class="empty">Bill is empty.<br>Search a medicine and tap it.</div>')+'</div></div></div>'},
purchase:function(){
  return '<div class="sheet"><label>Medicine</label><select id="pi">'+(D.items.length?D.items.map(function(i){return '<option value="'+i.id+'">'+esc(i.name)+'</option>'}).join(''):'<option value="">Add a medicine first</option>')+'</select><button class="link" onclick="go(\'items\')">+ New medicine</button>'+
  '<div class="two"><div><label>Batch no.</label><input id="pb"></div><div><label>Expiry date</label><input id="pe" type="date"></div><div><label>Quantity</label><input id="pqn" type="number" inputmode="numeric"></div><div><label>Buy rate (each)</label><input id="pr" type="number" inputmode="decimal"></div></div><label>MRP (each)</label><input id="pm" type="number" inputmode="decimal"><label>Supplier (optional)</label><input id="sp"><button class="btn" onclick="addPur()">Add to Stock</button></div>'},
items:function(){
  return '<div class="sheet"><label>Medicine name</label><input id="n" placeholder="Dolo 650"><label>Salt / composition (optional)</label><input id="s" placeholder="Paracetamol 650mg"><label>Barcode (optional)</label><input id="bc" placeholder="Scan or type barcode"><div class="two"><div><label>GST %</label><select id="g"><option>0</option><option>5</option><option selected>12</option><option>18</option></select></div><div><label>Alert when stock is</label><input id="m" type="number" inputmode="numeric" value="10"></div></div><button class="btn" onclick="addItem()">Save Medicine</button><h2>All medicines</h2>'+
  (D.items.length?D.items.map(function(i){return '<div class="li"><div class="m"><b>'+esc(i.name)+'</b><span>'+esc(i.salt||'—')+' · GST '+i.gst+'%</span></div><button class="link" style="color:var(--bad)" onclick="delItem(\''+i.id+'\')">Delete</button></div>'}).join(''):'<div class="empty">No medicines yet.</div>')+'</div>'},
expiry:function(){var l=expList();return '<div class="sheet"><p style="color:var(--mute);font-size:14px">Stock expiring in 90 days or already expired.</p>'+(l.length?l.map(function(b){var i=item(b.itemId),d=dto(b.exp);return '<div class="li"><div class="m"><b>'+esc(i?i.name:'?')+'</b><span>Batch '+esc(b.batch)+' · '+b.exp+'</span><br><span class="tag '+(d<0?'bad':'warn')+'">'+(d<0?'Expired':'In '+d+' days')+'</span></div><div class="q">'+b.qty+'<small>units</small></div></div>'}).join(''):'<div class="empty">No expiry problem. 👍</div>')+'</div>'},
short:function(){var l=shortList();return '<div class="sheet"><p style="color:var(--mute);font-size:14px">Medicines to order soon.</p>'+(l.length?l.map(function(i){return '<div class="li"><div class="m"><b>'+esc(i.name)+'</b><span>Alert level '+i.min+'</span></div><div class="q" style="color:var(--bad)">'+qty(i.id)+'<small>left</small></div></div>'}).join(''):'<div class="empty">All medicines have enough stock. 👍</div>')+(l.length?'<button class="btn" onclick="waOrder()">Share order list on WhatsApp</button>':'')+'</div>'},
report:function(){
  function agg(f){var l=okS().filter(function(s){return f(s.date)});return {a:l.reduce(function(x,s){return x+s.total},0),p:l.reduce(function(x,s){return x+s.profit},0),n:l.length}}
  var d=today(),R=[['Today',agg(function(x){return x===d})],['This month',agg(function(x){return x.slice(0,7)===d.slice(0,7)})],['This year',agg(function(x){return x.slice(0,4)===d.slice(0,4)})]];
  return '<div class="sheet rg" style="padding-top:16px">'+R.map(function(r){return '<div class="rep"><h3>'+r[0]+'</h3><div class="g"><div><b>'+rs(r[1].a)+'</b><span>Sale</span></div><div><b>'+rs(r[1].p)+'</b><span>Profit</span></div><div><b>'+r[1].n+'</b><span>Bills</span></div></div></div>'}).join('')+'</div>'+gstRep()+'<div class="sheet"><h2>Recent bills</h2>'+(D.sales.length?D.sales.slice(-10).reverse().map(function(s){return '<div class="li" onclick="showBill('+s.no+')" style="cursor:pointer"><div class="m"><b>Bill #'+s.no+' · '+esc(s.cust)+'</b><span>'+s.date+' · tap to view / print</span></div><div class="q">'+rs(s.total)+'</div></div>'}).join(''):'<div class="empty">No bills yet.</div>')+'</div>'},
credit:function(){var m={};okS().forEach(function(s){if(s.pay==='Credit')m[s.cust]=(m[s.cust]||0)+s.total});pays().forEach(function(p){m[p.c]=(m[p.c]||0)-p.a});var k=Object.keys(m).filter(function(x){return m[x]>0.5});
  return '<div class="sheet"><p style="color:var(--mute);font-size:14px">Customers who still owe money (credit bills).</p>'+(k.length?k.map(function(c){return '<div class="li"><div class="m"><b>'+esc(c)+'</b></div><div class="q" style="color:var(--bad)">'+rs(m[c])+'</div><button class="link" onclick="recvPay('+JSON.stringify(c).replace(/"/g,'&quot;')+')">Received</button></div>'}).join(''):'<div class="empty">No pending udhaar.</div>')+'</div>'},
settings:function(){var h=D.shop||{};return '<div class="sheet"><label>Shop name</label><input id="sn" value="'+esc(h.name||'')+'"><label>Address</label><input id="sa" value="'+esc(h.addr||'')+'"><div class="two"><div><label>Phone</label><input id="sph" value="'+esc(h.phone||'')+'"></div><div><label>GSTIN</label><input id="sg" value="'+esc(h.gstin||'')+'"></div></div><label>Drug licence no.</label><input id="sdl" value="'+esc(h.dl||'')+'"><button class="btn" onclick="saveShop()">Save shop details</button><h2>Backup</h2><p style="color:var(--mute);font-size:14px">Data is saved in this browser only. Download a backup every week and keep it in Google Drive or WhatsApp. '+(D.lastBackup?'Last backup: '+D.lastBackup:'No backup taken yet.')+'</p><button class="btn" onclick="backup()">Download Backup</button><label>Restore from a backup file</label><input type="file" accept=".json" onchange="restore(this)"></div>'},
bill:function(){var s=D.sales.find(function(x){return x.no===BILL});if(!s)return '<div class="empty">Bill not found.</div>';var h=D.shop||{},g=0,L=s.lines||[];
  L.forEach(function(l){var a=l.q*l.mrp*(1-s.disc/100);g+=a-a/(1+l.gst/100)});
  return '<div class="sheet" style="padding-top:16px"><div class="bill"><h3>'+esc(h.name||'Medical Store')+'</h3><div class="c">'+esc(h.addr||'')+(h.phone?' · '+esc(h.phone):'')+'</div><div class="c">'+(h.gstin?'GSTIN: '+esc(h.gstin):'')+(h.dl?' · DL: '+esc(h.dl):'')+'</div><div class="tt" style="margin-top:8px"><span>Bill #'+s.no+'</span><span>'+s.date+'</span></div><div>Customer: '+esc(s.cust)+'</div>'+(s.doc?'<div>Doctor: '+esc(s.doc)+'</div>':'')+'<div>Payment: '+esc(s.pay||'Cash')+(s.ret?' · RETURNED':'')+'</div><table><tr><th>Medicine</th><th>Batch</th><th>Exp</th><th class="r">Qty</th><th class="r">Amt</th></tr>'+L.map(function(l){return '<tr><td>'+esc(l.name)+'</td><td>'+esc(l.batch)+'</td><td>'+l.exp.slice(0,7)+'</td><td class="r">'+l.q+'</td><td class="r">'+rp(l.q*l.mrp)+'</td></tr>'}).join('')+'</table><div class="tt"><span>Subtotal</span><span>'+rp(s.sub)+'</span></div>'+(s.disc?'<div class="tt"><span>Discount '+s.disc+'%</span><span>-'+rp(s.sub-s.total)+'</span></div>':'')+'<div class="tt"><span>CGST (included)</span><span>'+rp(g/2)+'</span></div><div class="tt"><span>SGST (included)</span><span>'+rp(g/2)+'</span></div><div class="tt gt"><span>Total</span><span>'+rp(s.total)+'</span></div><div class="c" style="margin-top:10px">Thank you. Get well soon.</div></div><button class="btn noprint" onclick="window.print()">Print Bill</button><button class="btn noprint" onclick="waBill('+s.no+')">Send on WhatsApp</button>'+(s.ret?'':'<button class="link noprint" style="color:var(--bad)" onclick="retBill('+s.no+')">Return this bill</button>')+'<button class="link noprint" onclick="go(\'home\')">Done</button></div>'}
};
function fillStock(q){q=q.toLowerCase();var l=D.items.filter(function(i){return (i.name+' '+(i.salt||'')+' '+(i.bc||'')).toLowerCase().indexOf(q)>-1});
  $('lst').innerHTML=l.length?l.map(function(i){var n=qty(i.id),lb=live(i.id),st=n<=i.min?'<span class="tag bad">Short stock</span>':(lb.length&&dto(lb[0].exp)<=60?'<span class="tag warn">Expires in '+dto(lb[0].exp)+' days</span>':'<span class="tag">OK</span>');
    return '<div class="li"><div class="m"><b>'+esc(i.name)+'</b><span>'+esc(i.salt||'')+'</span><br>'+st+'</div><div class="q">'+n+'<small>units</small></div></div>'}).join(''):'<div class="empty">No medicine found.<br>Add it from Home → Medicines.</div>'}
function pk(e){if(e.key==='Enter'&&FIRST)addCart(FIRST)}
function fillPick(q){q=q.toLowerCase();FIRST=null;if(!q){$('pick').innerHTML='';return}
  var l=D.items.filter(function(i){return (i.name+' '+(i.salt||'')+' '+(i.bc||'')).toLowerCase().indexOf(q)>-1}).slice(0,6),sb=[];
  l.forEach(function(i){if(qty(i.id)===0)subs(i).forEach(function(x){if(l.indexOf(x)<0&&sb.indexOf(x)<0)sb.push(x)})});
  var all=l.concat(sb),f=all.find(function(i){return qty(i.id)>0});FIRST=f?f.id:(all.length?all[0].id:null);
  $('pick').innerHTML=all.map(function(i){var n=qty(i.id),b=live(i.id)[0],s=sb.indexOf(i)>-1;return '<div class="li" onclick="addCart(\''+i.id+'\')" style="cursor:pointer"><div class="m"><b>'+esc(i.name)+'</b><span>'+(s?'<span class="tag">Substitute</span> ':'')+(b?rs(b.mrp)+' · ':'')+(n?n+' in stock':'Out of stock')+'</span></div><div class="ic" style="width:40px;height:40px;font-size:22px;margin:0;color:var(--p)">+</div></div>'}).join('')||'<div class="empty">Not found</div>'}
function addCart(id){var i=item(id),b=live(id)[0],c=cart.find(function(x){return x.id===id});
  if(!b){alert('No stock for '+i.name+'.');return}
  if(c){if(c.q+1>qty(id)){alert('Only '+qty(id)+' in stock.');return}c.q++}else cart.push({id:id,name:i.name,q:1,mrp:b.mrp,gst:i.gst});draw()}
function chg(x,d){var c=cart[x];if(d>0&&c.q+1>qty(c.id)){alert('Only '+qty(c.id)+' in stock.');return}c.q+=d;if(c.q<=0)cart.splice(x,1);draw()}
function cartSum(){return cart.reduce(function(a,c){return a+c.q*c.mrp},0)}
function upd(){var d=Math.min(100,Math.max(0,+$('ds').value||0));$('gt').textContent=rs(cartSum()*(1-d/100))}
function finish(){if($('pm2').value==='Credit'&&!$('cn').value.trim()){alert('Enter customer name for a credit bill.');return}
  var d=Math.min(100,Math.max(0,+$('ds').value||0)),f=1-d/100,pf=0,sub=0,lines=[];
  cart.forEach(function(c){var need=c.q;sub+=c.q*c.mrp;live(c.id).forEach(function(b){if(need<=0)return;var u=Math.min(b.qty,need);b.qty-=u;need-=u;pf+=u*(c.mrp*f-b.rate);lines.push({name:c.name,q:u,mrp:c.mrp,gst:c.gst,batch:b.batch,exp:b.exp,bid:b.id})})});
  var no=D.sales.length+1;D.sales.push({no:no,date:today(),cust:($('cn').value.trim()||'Walk-in'),ph:$('cph').value.trim(),doc:$('dr').value.trim(),pay:$('pm2').value,lines:lines,sub:sub,disc:d,total:sub*f,profit:pf});cart=[];save();showBill(no)}
function showBill(n){BILL=n;go('bill')}
function saveShop(){D.shop={name:$('sn').value.trim(),addr:$('sa').value.trim(),phone:$('sph').value.trim(),gstin:$('sg').value.trim(),dl:$('sdl').value.trim()};save();alert('Shop details saved.');go('home')}
function backup(){D.lastBackup=today();save();var b=new Blob([JSON.stringify(D)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='medical-backup-'+today()+'.json';a.click();draw()}
function restore(inp){var f=inp.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var x=JSON.parse(r.result);if(!x.items||!x.batches||!x.sales)throw 0;if(!confirm('Replace ALL current data with this backup?'))return;D=x;D.shop=D.shop||{};D.pay=D.pay||[];save();alert('Backup restored.');go('home')}catch(e){alert('This is not a valid backup file.')}};r.readAsText(f)}
function addPur(){var id=$('pi').value,b=$('pb').value.trim(),e=$('pe').value,q=+$('pqn').value,r=+$('pr').value,m=+$('pm').value;
  if(!id||!b||!e||q<=0||!r||!m){alert('Please fill medicine, batch, expiry, quantity, rate and MRP.');return}
  D.batches.push({id:uid(),itemId:id,batch:b,exp:e,qty:q,rate:r,mrp:m,supplier:$('sp').value.trim(),date:today()});save();alert('Stock added.');go('stock')}
function addItem(){var n=$('n').value.trim();if(!n){alert('Enter the medicine name.');return}
  D.items.push({id:uid(),name:n,salt:$('s').value.trim(),bc:$('bc').value.trim(),gst:+$('g').value,min:+$('m').value||0});save();draw()}
function delItem(id){if(!confirm('Delete this medicine and its stock?'))return;D.items=D.items.filter(function(i){return i.id!==id});D.batches=D.batches.filter(function(b){return b.itemId!==id});save();draw()}
draw();
